### ISSUE TITLE
Fails to install with time >= 1.5 as a dependency

### ISSUE THREAD

**Issue by benstevens48** [bos/mysql-simple#16]
In the module Database.MySQL.Simple.Result, the function defaultTimeLocale is imported via import System.Locale (defaultTimeLocale). However, in line 154 it is used as follows.

parseTime defaultTimeLocale "%F %T" (B8.unpack bs)

The problem is parseTime expects the data type Data.Time.Format.Locale.TimeLocale not System.Locale.TimeLocale if the time package >= 1.5 is used.

This makes it impossible to use the mysql-simple package with the latest versions of the time package, which seems like quite a big issue.

**Comment by bos** [comment]
Thanks for the report; I've issued a point release with the fix.

**Comment by benstevens48** [comment]
Hi,

 

Thanks for the quick fix. I can confirm it works for me now.

 

There is an issue with using the mysql package on Mac OS X though (I see others have encountered it as well). The only way to get it to compile is to specify the MySQL library path in the DYLD_LIBRARY_PATH environment variable, which is not ideal as it has the potential to break other stuff. I think one of the problems in compiling may be due to the fact that the mysql_config program specifies something like libmysqlclient.dylib as a library it depends on, but this is actually symlinked to libmysqlclient.18.dylib, and the library name is libmysqlclient.18.dylib, and this can’t be found during the install process. I don’t really understand it though. But there is obviously going to be a problem at runtime as well if the program is run on another machine and the paths to the libraries are different. I’m not sure if it’s possible to do anything about this.

 

Best wishes,

 

Ben
